### ISSUE TITLE
Missing `tests/__init__.py` from pypi source distribution

### ISSUE THREAD

**Issue by h7x4** [TakWolf/pixel-font-builder#4]
I am not able to run tests from source distribution on pypi.

This is also a problem with the following:
- bdffont
- character-encoding-utils
- unidata-blocks

They seem to be missing `tests/__init__.py`

### Steps to reproduce:

```console
curl -o bdffont.tar.gz "https://files.pythonhosted.org/packages/dd/39/6453288d95b4fb051038440d10dbf5db5a3496e3b83ca53c27a26350aca2/bdffont-0.0.13.tar.gz"
tar xvzf bdffont.tar.gz
cd bdffont-0.0.13
python -m pytest
```

**Comment by TakWolf** [comment]
It seems that build tools only pack `tests/test_` prefix file (which is also the convention of pytest) and ignore other files.
The execution of unit tests does not require `__init__.py` (see: https://docs.pytest.org/en/latest/explanation/goodpractices.html#tests-outside-application-code). I added some common scripts in `__init__.py`, this caused the test to fail.

I'm not sure what is the correct practice.

**Comment by h7x4** [comment]
I think I see 3 solutions:

1. Create `conftest.py` (or `common.py` or something) and put the contents of `__init__.py` there. Then the common parts will not be removed.
2. Create `conftest.py` and pass the variables in through test fixtures. While this is the "proper" solution, it will probably vendor lock you to pytest.
3. Figure out how to make buildtools keep `__init__.py` when uploading to pypi.

**Comment by TakWolf** [comment]
It seems that build doesn't pack `conftest.py` either by default.

Currently, I only need a common path variable config. Pytest has a temporary directories: https://docs.pytest.org/en/6.2.x/tmpdir.html#the-default-base-temporary-directory

This can solve the problem.

But I'm still not sure what the best practices are.

I am researching the following document:
https://docs.pytest.org/en/6.2.x/fixture.html

**Comment by h7x4** [comment]
These docs were helpful:

- https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute
- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

It seems like `python -m build` is already implicitly using setuptools, but it doesn't hurt to specify it.

Maybe something like this could be a solution?

```diff
diff --git c/pyproject.toml i/pyproject.toml
index 178c1eb..97cc417 100644
--- c/pyproject.toml
+++ i/pyproject.toml
@@ -1,3 +1,7 @@
+[build-system]
+requires = ["setuptools", "setuptools-scm"]
+build-backend = "setuptools.build_meta"
+
 [project]
 name = "bdffont"
 version = "0.0.13"
@@ -27,3 +31,6 @@ issues = "https://github.com/TakWolf/bdffont/issues"
 pythonpath = [
     "src",
 ]
+
+[tool.setuptools.package-data]
+"*" = ["tests/*"]
```

**Comment by TakWolf** [comment]
I found the actual situation to be more complex. 

Some tests require recesource files (now in assets dirs).
If unit testing can be executed, it means that you must also upload these static resource files. Is this the correct way?
If that,  I would prefer to disable upload testing. Because this will increase the size of the package.

Now https://github.com/TakWolf/bdffont and https://github.com/TakWolf/pixel-font-builder need static files to support tests.

**Comment by h7x4** [comment]
I think that these resource files are strictly test data, and should be considered part of the tests. I think it's probably fine to upload them if they are required to run the tests.

There does not seem to be any convention or correct way. Some consider their source distributions to be just a tarball of their code and thus includes both tests and docs, while others create a more cleaned-up version of the source code. Source: https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578/4

I guess you could make an argument that since setuptools includes `test/test*` by default, the tests should be included by default?

This should only increase the size of the source distributions, the wheel should not have tests.

I think it's up to you whether you want to include the tests or not.

**Comment by TakWolf** [comment]
I have publish a new version https://github.com/TakWolf/pixel-font-builder/releases/tag/0.0.10

The unittest code is complete.

Currently, I have explicitly specified the `build-backend`: 
https://github.com/TakWolf/pixel-font-builder/blob/master/pyproject.toml#L1

Whether it's hashing or setuptools or others, build will pack all files use vcs define by default, see: https://hatch.pypa.io/latest/config/build/#vcs

I keep this behavior, with no other configs.

This is the structure:

<img width="562" alt="image" src="https://github.com/TakWolf/pixel-font-builder/assets/6064962/487c7033-7858-4afb-bdcc-6e7e6e803ae1">

**Comment by TakWolf** [comment]
About `tests/__init__.py`,

In pytest good practices example, this file is not included. (But I didn't see a clear explanation that the file shouldn't exist)

https://docs.pytest.org/en/latest/explanation/goodpractices.html#tests-outside-application-code

Hatch will create it, see: https://hatch.pypa.io/latest/intro/#new-project

```
hatch-demo
├── src
│   └── hatch_demo
│       ├── __about__.py
│       └── __init__.py
├── tests
│   └── __init__.py
├── LICENSE.txt
├── README.md
└── pyproject.toml
```

[flask/tests](https://github.com/pallets/flask/tree/main/tests) have no `__init__.py`
[django/tests](https://github.com/django/django/tree/main/tests) have no `__init__.py` on root, but has in child module dir.
[fonttools/Tests](https://github.com/fonttools/fonttools/tree/main/Tests) have no `__init__.py`, include child modules.

I have also seen some discussions, but there is no clear conclusion. Actually, this does not affect the test run.

I have temporarily removed the `__init__.py` file. 
But if it cannot be clearly determined that it has side effects, I may add it back later.

**Comment by h7x4** [comment]
> I have publish a new version https://github.com/TakWolf/pixel-font-builder/releases/tag/0.0.10

Thank you! That solves a lot of my problems!

> I have temporarily removed the `__init__.py` file.
> But if it cannot be clearly determined that it has side effects, I may add it back later.

That is fine with me. As long as it is either possible or explicitly not possible to build the tests in the sdists, I'm happy! Nice to see a specified built tool as well.

There's another issue now though, where the naming is inconsistent. `pixel-font-builder`s sdist is called `pixel_font_builder-0.0.10.tar.gz` (with underscores), while `character-encoding-utils`' sdist is called `character-encoding-utils-0.0.5.tar.gz` (with hyphens). Would you like me to create a new issue?

**Comment by TakWolf** [comment]
> There's another issue now though, where the naming is inconsistent. pixel-font-builders sdist is called pixel_font_builder-0.0.10.tar.gz (with underscores), while character-encoding-utils' sdist is called character-encoding-utils-0.0.5.tar.gz (with hyphens). Would you like me to create a new issue?

I noticed this problem, this is the default behavior of hatch, different from setuptools.

- character-encoding-utils
- unidata-blocks

I didn't publish these two because there were no substantial changes. I will publish them new version later.

**Comment by h7x4** [comment]
> I will publish them new version later.

Great! Thank you!

Closing
